name: open_food_facts_api_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  flutter:
    sdk: flutter
  open_food_facts_api:
    path: ../open_food_facts_api
  openfoodfacts: ^3.0.0
  products_api:
    path: ../products_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
